"""ActionRecord model for persistent learning data.

This module defines the ActionRecord entity schema using SQLModel.
Stores the history of all autonomous actions and their outcomes
to enable learning and confidence improvement over time.
"""

from datetime import datetime

from sqlmodel import Field, SQLModel


class ActionRecord(SQLModel, table=True):
    """Database model for recording autonomous action outcomes.

    Used by the Learning Service to:
    - Track success/failure rates per action type
    - Calculate confidence improvements over time
    - Enable cross-agent learning
    - Generate trend analysis

    Attributes:
        id: Primary key
        action_type: Type of action (DEPLOY, ROLLBACK, etc.)
        agent_type: Which agent executed the action
        domain: Domain category (deploy, monitoring, integration)
        decision_reason: Why this action was decided
        confidence_score: Confidence level when decision was made
        autonomous: Whether executed autonomously or with approval
        success: Whether the action succeeded
        result_summary: Brief summary of the outcome
        error_message: Error details if action failed
        execution_time_ms: How long the action took
        affected_services: List of services impacted
        timestamp: When the action was executed
        created_at: Record creation timestamp

    Example:
        >>> record = ActionRecord(
        ...     action_type="DEPLOY",
        ...     agent_type="DeployAgent",
        ...     domain="deploy",
        ...     decision_reason="Health check failure recovery",
        ...     confidence_score=0.85,
        ...     autonomous=True,
        ...     success=True,
        ...     result_summary="Deployment succeeded",
        ...     execution_time_ms=12500,
        ...     affected_services="main-api",
        ...     timestamp=datetime.now()
        ... )
    """

    id: int | None = Field(default=None, primary_key=True)
    action_type: str = Field(index=True, description="DEPLOY, ROLLBACK, CREATE_ISSUE, etc.")
    agent_type: str = Field(
        default="AutonomousController",
        index=True,
        description="DeployAgent, MonitoringAgent, etc.",
    )
    domain: str = Field(
        default="system", index=True, description="deploy, monitoring, integration, system"
    )
    decision_reason: str = Field(default="", description="Why this action was decided")
    confidence_score: float = Field(default=0.0, description="Confidence level 0.0-1.0")
    autonomous: bool = Field(default=False, description="True if auto-executed")
    success: bool = Field(default=False, description="True if action succeeded")
    result_summary: str = Field(default="", description="Brief outcome summary")
    error_message: str | None = Field(default=None, description="Error details if failed")
    execution_time_ms: int = Field(default=0, description="Execution duration in ms")
    affected_services: str = Field(default="", description="Comma-separated service list")
    timestamp: datetime = Field(default_factory=datetime.utcnow, index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        """SQLModel configuration."""

        extra = "forbid"


class ActionStats(SQLModel):
    """Statistics for action performance.

    Not a database table - used for aggregated analysis.

    Attributes:
        action_type: Type of action
        agent_type: Which agent
        total_count: Total number of executions
        success_count: Number of successful executions
        failure_count: Number of failures
        success_rate: Success percentage
        avg_confidence: Average confidence score
        avg_execution_time_ms: Average execution time
        last_executed: Most recent execution timestamp
        confidence_trend: Improving, stable, or declining
    """

    action_type: str
    agent_type: str = "all"
    total_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    success_rate: float = 0.0
    avg_confidence: float = 0.0
    avg_execution_time_ms: float = 0.0
    last_executed: datetime | None = None
    confidence_trend: str = "stable"  # improving, stable, declining


class LearningInsight(SQLModel):
    """Learning insight for decision improvement.

    Not a database table - generated by analysis.

    Attributes:
        insight_type: Category of insight
        description: Human-readable explanation
        recommendation: Suggested action
        impact_level: How important this insight is
        action_types: Which actions this affects
        data_points: Number of records analyzed
        generated_at: When insight was generated
    """

    insight_type: str  # success_rate_trend, confidence_adjustment, agent_performance
    description: str
    recommendation: str
    impact_level: str = "medium"  # low, medium, high, critical
    action_types: list[str] = []
    data_points: int = 0
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class ConfidenceAdjustment(SQLModel):
    """Suggested confidence adjustment based on learning.

    Not a database table - calculated recommendation.

    Attributes:
        action_type: Which action type
        current_base: Current base confidence
        recommended_base: Recommended adjustment
        reason: Why this adjustment is suggested
        sample_size: Number of actions analyzed
        time_period_days: Analysis window
    """

    action_type: str
    current_base: float
    recommended_base: float
    reason: str
    sample_size: int
    time_period_days: int = 7
